# Generated by Django 5.2.8 on 2026-05-26 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='Enable WhatsApp Notifications')),
                ('whatsapp_api_key', models.CharField(blank=True, help_text='Meta WhatsApp Business API bearer token from Meta Developer Console', max_length=500, null=True, verbose_name='WhatsApp API Key (Bearer Token)')),
                ('whatsapp_phone_number_id', models.CharField(blank=True, help_text='Your WhatsApp Business phone number ID from Meta Business Suite', max_length=100, null=True, verbose_name='WhatsApp Phone Number ID')),
                ('whatsapp_business_account_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp Business Account ID')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Enable Email Notifications')),
                ('gmail_from_name', models.CharField(default='Passly Hai', max_length=100, verbose_name='Sender Name')),
                ('gmail_from_email', models.EmailField(blank=True, help_text='Email address that appears in the "From" field', max_length=254, null=True, verbose_name='From Email Address')),
                ('gmail_host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='SMTP Host')),
                ('gmail_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('gmail_username', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmail Username / Email')),
                ('gmail_password', models.CharField(blank=True, help_text='Use an App Password — NOT your regular Gmail password. Generate at: Google Account → Security → 2-Step Verification → App passwords', max_length=200, null=True, verbose_name='Gmail App Password')),
                ('gmail_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('razorpay_enabled', models.BooleanField(default=True, verbose_name='Enable Razorpay Payments')),
                ('razorpay_key_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razorpay Key ID')),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razorpay Key Secret')),
                ('site_name', models.CharField(default='Passly Hai', max_length=100, verbose_name='Site Name')),
                ('site_url', models.URLField(default='http://127.0.0.1:8000', verbose_name='Site URL')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Support Email')),
                ('support_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Support Phone')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_footer_code',
            field=models.TextField(blank=True, help_text='Raw HTML/JS added before </body>', verbose_name='Custom Footer Code'),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_header_code',
            field=models.TextField(blank=True, help_text='Raw HTML/JS added inside <head>', verbose_name='Custom Header Code'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('regular', 'Regular / Recurring')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Google Analytics / GTM ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Admin Approved'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Free Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_pixel_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meta Pixel ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/800x400/7C3AED/ffffff?text=Event+Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=20.5937, help_text='Latitude for map location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=78.9629, help_text='Longitude for map location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount (₹)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_uses', models.IntegerField(default=100)),
                ('used_count', models.IntegerField(default=0, editable=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum booking amount required to use this coupon', max_digits=10)),
                ('event', models.ForeignKey(blank=True, help_text='Leave blank to apply to all events', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='events.event')),
            ],
            options={
                'verbose_name': 'Coupon Code',
                'verbose_name_plural': 'Coupon Codes',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.couponcode'),
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('mobile_number', models.CharField(max_length=15)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=11, verbose_name='IFSC Code')),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('pan_card_number', models.CharField(blank=True, max_length=10, verbose_name='PAN Card Number')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, verbose_name='Aadhaar Number')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organizer Profile',
                'verbose_name_plural': 'Organizer Profiles',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(choices=[('verifier', 'Ticket Verifier / QR Scanner'), ('manager', 'Event Manager'), ('support', 'Support Staff')], default='verifier', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium'), ('vip', 'VIP')], default='normal', max_length=20)),
                ('name', models.CharField(help_text='e.g., General Admission, VIP Pass', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='events.tickettype'),
        ),
    ]
