# Generated by Django 5.2.14 on 2026-06-06 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_payout_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Manual / Imported Booking'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='bank_account_number_confirm',
            field=models.CharField(blank=True, help_text='Re-enter account number to confirm', max_length=20, verbose_name='Confirm Account Number'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='About / Description'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='gst_number',
            field=models.CharField(blank=True, help_text='15-digit GST Identification Number (optional)', max_length=15, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Show in Public Directory'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='profile_image',
            field=models.URLField(blank=True, verbose_name='Profile Image URL'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum price organisers can set for paid tickets', max_digits=10, verbose_name='Minimum Ticket Price (₹)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payout_charge_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage deducted from each payout as processing fee', max_digits=5, verbose_name='Payout Processing Charge (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform fee percentage charged on each ticket sale', max_digits=5, verbose_name='Platform Fee (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reminder_advance_cost',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Cost per attendee for advance WhatsApp reminder', max_digits=8, verbose_name='Advance Reminder Cost (₹)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reminder_normal_cost',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Cost per attendee for normal email reminder', max_digits=8, verbose_name='Normal Reminder Cost (₹)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django user account for this team member to log in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Linked Login Account'),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Beneficiary Name'),
        ),
        migrations.CreateModel(
            name='EventDataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_delete_at', models.DateTimeField()),
                ('email_sent', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('sent_to_email', models.EmailField(blank=True, help_text='Email address the export was sent to', max_length=254)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Data Export',
                'verbose_name_plural': 'Event Data Exports',
                'ordering': ['-exported_at'],
            },
        ),
    ]
