# Generated by Django 5.2.14 on 2026-06-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_new_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scan_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this ticket has been scanned at entry'),
        ),
    ]
